<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // General Settings
            [
                'key' => 'app_name',
                'value' => 'ZalvlmaX Quiz',
                'type' => 'string',
                'group' => 'general',
                'description' => 'Nama aplikasi',
                'is_public' => true,
            ],
            [
                'key' => 'app_description',
                'value' => 'Platform Kuis Online Profesional',
                'type' => 'string',
                'group' => 'general',
                'description' => 'Deskripsi aplikasi',
                'is_public' => true,
            ],
            [
                'key' => 'app_logo',
                'value' => null,
                'type' => 'file',
                'group' => 'general',
                'description' => 'Logo aplikasi',
                'is_public' => true,
            ],
            [
                'key' => 'app_favicon',
                'value' => null,
                'type' => 'file',
                'group' => 'general',
                'description' => 'Favicon aplikasi',
                'is_public' => true,
            ],
            [
                'key' => 'app_timezone',
                'value' => 'Asia/Jakarta',
                'type' => 'string',
                'group' => 'general',
                'description' => 'Timezone aplikasi',
                'is_public' => false,
            ],

            // Quiz Settings
            [
                'key' => 'default_quiz_duration',
                'value' => '30',
                'type' => 'integer',
                'group' => 'quiz',
                'description' => 'Durasi default kuis (menit)',
                'is_public' => false,
            ],
            [
                'key' => 'default_passing_score',
                'value' => '60',
                'type' => 'integer',
                'group' => 'quiz',
                'description' => 'Nilai minimum kelulusan default (%)',
                'is_public' => false,
            ],
            [
                'key' => 'default_max_attempts',
                'value' => '3',
                'type' => 'integer',
                'group' => 'quiz',
                'description' => 'Maksimal percobaan default',
                'is_public' => false,
            ],
            [
                'key' => 'enable_realtime_monitoring',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'quiz',
                'description' => 'Aktifkan monitoring realtime',
                'is_public' => false,
            ],
            [
                'key' => 'show_leaderboard',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'quiz',
                'description' => 'Tampilkan leaderboard publik',
                'is_public' => true,
            ],

            // Email Settings
            [
                'key' => 'mail_from_address',
                'value' => 'noreply@zalvlmax.com',
                'type' => 'string',
                'group' => 'email',
                'description' => 'Alamat email pengirim',
                'is_public' => false,
            ],
            [
                'key' => 'mail_from_name',
                'value' => 'ZalvlmaX Quiz',
                'type' => 'string',
                'group' => 'email',
                'description' => 'Nama pengirim email',
                'is_public' => false,
            ],
            [
                'key' => 'send_quiz_result_email',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'email',
                'description' => 'Kirim email hasil kuis',
                'is_public' => false,
            ],

            // Report Settings
            [
                'key' => 'report_export_expiry_days',
                'value' => '7',
                'type' => 'integer',
                'group' => 'report',
                'description' => 'Masa berlaku file ekspor (hari)',
                'is_public' => false,
            ],
            [
                'key' => 'pdf_header_text',
                'value' => 'Laporan ZalvlmaX Quiz',
                'type' => 'string',
                'group' => 'report',
                'description' => 'Teks header laporan PDF',
                'is_public' => false,
            ],
            [
                'key' => 'pdf_footer_text',
                'value' => 'Generated by ZalvlmaX Quiz System',
                'type' => 'string',
                'group' => 'report',
                'description' => 'Teks footer laporan PDF',
                'is_public' => false,
            ],

            // Security Settings
            [
                'key' => 'session_lifetime',
                'value' => '120',
                'type' => 'integer',
                'group' => 'security',
                'description' => 'Durasi session (menit)',
                'is_public' => false,
            ],
            [
                'key' => 'password_min_length',
                'value' => '8',
                'type' => 'integer',
                'group' => 'security',
                'description' => 'Panjang minimum password',
                'is_public' => false,
            ],
            [
                'key' => 'login_attempts_limit',
                'value' => '5',
                'type' => 'integer',
                'group' => 'security',
                'description' => 'Batas percobaan login',
                'is_public' => false,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
